### ISSUE TITLE
Links that ignore basePath?

### ISSUE THREAD

**Issue by kristiandupont** [kyeotic/raviger#105]
Thank you for creating Raviger, it is really close to the routing lib I was considering making out of frustrations with the existing ones! I really like the "cascading routes" concept  that allows me to extract, say, a tab-bar and its contents into a component and have it not care about which base route it sits on.

That said, there are times where I want to ignore the `basePath` and link to something outside the scope of the closest `useRoutes` context. I am currently solving that with relative links that go through parents (i.e. `../../account`), but that is now another way of coupling the specific path to my component. I tried overriding `basePath` with `'/'`, `''` and `null` which doesn't work (strips away the hostname and everything, or does nothing). Am I missing something fundamental, or should we consider adding an `isAbsolute` or similar property to `Link`? 

EDIT: I should add that I am happy to make a PR for this if you agree.

**Comment by kyeotic** [comment]
Thank you for the kind words ❤️ , its always nice to hear people are enjoying raviger.

Setting `basePath='/'` should work. If it isn't that's a bug that I would like to close. Can you create a reproduction? You can use [this codesandbox](https://codesandbox.io/s/bitter-frost-9ewru) as a template.

**Comment by kristiandupont** [comment]
https://codesandbox.io/s/loving-joliot-0lvb8?file=/src/App.js

If you click on the "Deep Root" link, and then on the "About" link under that, you will see the `DeepAbout` component render two links to contact, one that is inside the deep root (which is correct), and one that attempts to link to the outer contact url. The second one is broken.

**Comment by kyeotic** [comment]
@kristiandupont This proved very difficult to test due to jest/jsdom limitations on navigation, sorry for the delay.

A fix has been published under `2.5.5`

**Comment by kristiandupont** [comment]
Awesome, thank you!

There are a few other things that I've run into. Before I create separate tickets I'll just hijack this thread to hear your thoughts.

1) In `useRoutes`, I need to add an asterisk if a path might have search parameters. That feels incorrect to me -- I would expect anything after and including the `?` to be excluded from route matching.
2) It would be nice to have a general-purpose `useMatchesRoute` or similar. I have a situation where I want to make a tab indicate that it's active. I can't use the `<ActiveLink>` component because it's not a simple link, it's a `<nav>` with a link inside of it, and I need to style both.
3) Speaking of `<ActiveLink>`, I have a situation where I want to state an explicit text color when the link is inactive.  With the current api, I have to make the parent component set the default text color because if I do it in the `className`, that class happens to take priority over the one I want to use for the active case and so it never changes. This is a minor annoyance.
4) Should the `<Redirect>` detect/support base paths? It seems to me that would be the most symmetrical experience. So far, I have only used it for navigating outside of the current basepath scope, so it's not been an issue but it still surprised me. This would be a breaking change, obviously.

Again, I am not expecting you to just fix all of this and I am happy to create PR's for some of it if you think it would be the right change but I wanted to make sure it aligns with how you are thinking first.

**Comment by kyeotic** [comment]
1. Route matching should not take `?` into account and should not require a wildcard. This is definitely a bug, probably from the typescript conversion where the matcher was re-written. If you can open an issue with a repro I will get to it this week.
2. I think the use case makes sense, I would want to have a discussion about the API so that we consider sibling use cases. I'll start an issue for this.
3. Yes, this was a blind spot. It will probably introduce a breaking change, but I think it will be worth while. I have another breaking change waiting for `useLocationChange` that I've been sitting on for a while.

I appreciate the feedback here, it's clear you've tackled several use cases with the library. It's always nice to get more input 😄 . Before you open any PRs though I think we should start with an issue so we can agree on an API; I want to be very careful expanding the API surface of the library, especially with new concepts.
