### ISSUE TITLE
Could we have the location.search value returned next to path in useLocationChange?

### ISSUE THREAD

**Issue by Geddard** [kyeotic/raviger#115]
I'm doing some magic with this side effect to handle a referral value in the URL

And I need to compare the `window.location.search` value at the moment of the side effect callback being called, so it would be nice if we could get it next to path, maybe something like

```
useLocationChange(location, { ... } )
// and then we can just deconstruct what we need

useLocationChange({ pathname, search }, {...})
```

This way we don't need to use window.location.search if we need it's value and risk closure issues or someone moving this value out of the side effect thinking they can reuse a cached `const`

What do you think?

**Comment by kyeotic** [comment]
I've actually thought about this before. The name of the hook doesn't match its behavior, its really more of a `usePathChange` at the moment. I think it makes sense to have both, though it will be a breaking change.

Since there is another breaking change (#113), waiting in the wings it might be a good time to move forward with that. I do feel a bit guilty, the last breaking change was only 4 months ago...
