### ISSUE TITLE
useHistoryState

### ISSUE THREAD

**Issue by kyeotic** [kyeotic/raviger#117]
From [this comment](https://github.com/kyeotic/raviger/issues/113#issuecomment-1012333176)

`state` is accepted by `navigate` and set on history, but it is not accessible via the raviger API. We need a hook to expose it

```js
function useHistoryState() {
  const { state } = window.history;

  return state;
}
```

**Comment by dave-irvine** [comment]
If its just as simple as my hook example I'd be happy to do a PR for it?

**Comment by timkye-blueocean-ai** [comment]
Its not, since the example hook does not re-render after navigation. It's also going to require the changes I am making to `useLocationChange`, so any work there is going to be 80% conflict.

I started on this last night and got most of the functional code done, I just need to add tests. I plant to have a beta by middle of next week.

**Comment by kyeotic** [comment]
Its not, since the example hook does not re-render after navigation. It's also going to require the changes I am making to useLocationChange, so any work there is going to be 80% conflict.

I started on this last night and got most of the functional code done, I just need to add tests. I plant to have a beta by middle of next week.

**Comment by dave-irvine** [comment]
No worries, I'll leave it to you, just wanted to help out if I could :)

**Comment by kyeotic** [comment]
@dave-irvine v4 beta is up, you can see it in the PR for #118 

I would love to get some impressions from you
