### ISSUE TITLE
usePopState has wrong type definition, hook dependencies

### ISSUE THREAD

**Issue by yenoiwesa** [kyeotic/raviger#28]
Hey again!

So I have a use-case where a modal dialog contains links and the modal needs to close on any history change.

Rather than making my own listener, I went to see how `raviger` implements it, and found the nifty `usePopState` hook that does pretty much what I need. However I found the following:

1. `usePopState` is exposed but has no entry in the documentation. Is it part of the API? Is it fine to use it?

2. In the type definition, [it says](https://github.com/kyeotic/raviger/blob/master/types/raviger.d.ts#L44) that the `predicate` parameter is a function that returns a boolean, however, according to [the actual implementation](https://github.com/kyeotic/raviger/blob/master/src/path.js#L24) and usages across the library, it seems that it's only expecting a boolean.

3. The `predicate` parameter is not added to the dependencies of the `useEffect` hook, which means that if we need to change that condition after the initial render, it won't be taken into account.

4. I feel that `predicate` should be an optional argument, and could be moved to being the third parameter?

5. Probably have the same feeling about the first parameter. Seems like `basePath` could be optional and default to `''`.

Looking forward to hearing about your opinion on these 👍

**Comment by kyeotic** [comment]
Hey @yenoiwesa 👋 

1. It was exposed without a lot of thought. I'm glad you're brining this up before the [1.0 release](#27) is finalized, because I don't think I want to use that name if its part of the API. It does make sense in the API though, being a routing library and all. Any name suggestions?
2. This is a result of its exposure being under-considered. I wrote the type and the implementation on different nights. I'm leaning towards making it either, but if it's going to be one it should probably be the function predicate. This needs some freshly-caffeinated consideration.
3. This is an error.
4. Yes, it should be optional.
5. This is actually the stickiest point for me. Given that the hook will have access to the router-context it could just _fetch_ the `basePath`, if one exists. But then if you want to opt-out its awkward. But otherwise most times you will be calling `usePopState(useBathPath())`, which is also awkward. This needs more thought.

**Comment by kyeotic** [comment]
I'm thinking `useLocation` right now

**Comment by yenoiwesa** [comment]
Agree with all your points above.

Name-wise, `useLocation` makes sense, it's in line with the other hooks, `usePath` and `useQueryParams`.

Having the `onChange` callback passed to the hook is a great convenience so if you can, please keep this one in the new version :-)

Thanks again! 👍

**Comment by kyeotic** [comment]
@yenoiwesa Check out #29 and let me know what you think.

Its published with the first release candidate
```bash
npm i raviger@rc
# or
npm i raviger@1.0.0-rc.1
```

**Comment by yenoiwesa** [comment]
I just tested `useLocationChange` on `1.0.0-rc.1` and it does exactly what it says on the box!

Thanks heaps for the super fast changes, very much appreciated!
