### ISSUE TITLE
Route to modal

### ISSUE THREAD

**Issue by P4R4DiSi4C** [kyeotic/raviger#56]
Hello,

Thank you very much Kyeotic for bringing back and supporting hookrouter.

I'm currently trying to open a modal for a route without changing the current content of the page. Is it even possible with Raviger to do that or I should switch to another router ?

I've made an incomplete codesandbox since I'm quite stuck:

[https://codesandbox.io/s/distracted-snowflake-6cqcb?fontsize=14&hidenavigation=1&theme=dark](https://codesandbox.io/s/distracted-snowflake-6cqcb?fontsize=14&hidenavigation=1&theme=dark)

What would you do ? How ?

The final goal is to have:
- A login button that opens the modal
  - (If the user uses the direct url, it should open the Modal on the "/" root page)
- Have a register modal and a forgot password modal too.

Thank you so much for your suggestions and help

Regards

**Comment by kyeotic** [comment]
It sounds like you want the modal to operate independent from the route, so this isn't really a routing concern. What you probably want to do is manage the modal state with app-state (think redux) and open/close it with actions instead of navigation.

**Comment by P4R4DiSi4C** [comment]
It currently works like you stated.
I have a useState set on the modal that opens on Login button click and closes itself on backdrop click.

BUT

Instagram, Pinterest and Reddit for example, when you open an image on Instagram, they have a modal with the image and comments that load up + the url gets updated without changing the background route.

As shown at the beginning of this video: [https://youtu.be/EyjuRCxpf6Y](https://youtu.be/EyjuRCxpf6Y)

+ as shown on this other's library example: [https://reacttraining.com/react-router/web/example/modal-gallery](https://reacttraining.com/react-router/web/example/modal-gallery)

When you go to the gallery and open tomato, you get a modal + the correct url to the direct element.

It seems quite "tricky" to do even with others router library and I couldn't find any Hookrouter example.

It could be interesting to have an example too for Raviger if it's capable to do that.

**Comment by kyeotic** [comment]
Ah, I understand now. You want the URL to combine with the app-state.

1. User loads `/login` they get the full login page
2. User loads `/`, but then press login, url is set to `/login` and the user sees the login modal in front of the home page

Did I get that right? If so, you need to express this logic in the component that mounts the route. I can think of a couple ways to do this, but they all combine URL state (raviger) with app state (redux, useState, w/e).

You can change the `routes` object that `useRoutes` takes, so that its different for users that are logged in, or if they start on the login or home page, or if some `useState` state indicates it should. This is how you would control whether the route launched the full page or the modal.

**Comment by P4R4DiSi4C** [comment]
Exactly !

Alright, I will try that ! Thank you very much.
