### ISSUE TITLE
useLocationChange - check if the path exists

### ISSUE THREAD

**Issue by ariel-zap** [kyeotic/raviger#85]
Hi,
When using useLocationChange hook, I would like to check whether the path exists or not.
My goal is to create a 404 page and navigate to it programmatically (using "navigate" function) when the path doesn't exist.
I have read the documentation, but I didn't find any clue for that.

**Comment by kyeotic** [comment]
Sounds like a pretty straightforward thing to implement. 

```js
useLocationChange(path => {
  if (!isPathValid(path)) navigate('/404', true)
})
```

**Comment by ariel-zap** [comment]
Of course, it's possible, I was expecting a built-in raviger function. After all, it should know its registered routes (after calling "useRoutes" hook).
Thanks anyway.

**Comment by kyeotic** [comment]
I don't see the value in providing the route configuration as a parameter to `useLocationChange`, it can easily be provided by closure by the app.

The complexity on the other hand is high.

1. If nested in two `useRoutes`  are the routes merged, or or only the direct parent's routes provided?
1.a. If merged, how can the hook differentiate between parent-unknown and global-unknown? Does this matter?
1b. If only the direct parent's are provided then "path not exists" might be false in the global context. Do we need to provide a way to differentiate this?
2. If a `basePath` is set, are the routes presented with the `basePath` merged in, or are they provided as-defined so that they wont match the `path` that does have the `basePath` prefixed?
2a. If merged in how are wildcards on grandparents handled?
2b. If provided as-defined is a second utility function to match the path against `basePath`?
3. A common case for defining a wildcard route on the top-level is to provide a 404 page (the only more common would probably be a home page). Since the purpose here seems to be detecting 404 navigation should we indicate that the match occured on a wild card? Is there now a difference in "path not exists" when matching vs navigating?

I don't see a reasonable answer to most of these. What to do in these situations depends heavily on the app, which can answer these questions for itself rather easily. Raviger will have a hard time answering them for everyone.

**Comment by kyeotic** [comment]
I'm closing this issue, but I'm happy to re-open it later if someone wants to champion this.
