### ISSUE TITLE
useLocationChange is called on mount

### ISSUE THREAD

**Issue by yenoiwesa** [kyeotic/raviger#86]
Hi @kyeotic!

We have just upgraded `raviger` from version `1.6.0` to version `2.0.2` and we are facing a problem with a new behaviour introduced in `2.0.0` in `useLocationChange`.

`useLocationChange` will now call its callback argument on mount due to this `useLayoutEffect`:
https://github.com/kyeotic/raviger/blob/74e3b87eaf108d0950ab09f368f1f91f23345dcb/src/path.js#L93-L98

Is that completely intended? Or should that be a layout effect that only gets executed after the initial mount?

Our use case for `useLocationChange` is within modals that we want to close when the user hits the Back/Forward browser history buttons:
```jsx
// close the modal when the path has changed
useLocationChange(onClose);
```

With `2.0.2`, this code gets executed when the modal is mounted and thus it closes instantly.

**Comment by kyeotic** [comment]
Hey @yenoiwesa, sorry for the delay I was out sick last week. This looks like a gap in testing that should be closed, as it isn't checking in either direction. It seems like this should be a bug, since the behavior change would be breaking and wasn't including in the **breaking changes** for 2.0.

I may not have a chance to get to this until wednesday, but I would take a PR for it.

**Comment by yenoiwesa** [comment]
Hi @kyeotic, hope you feel better :-)

Sorry I didn't have time to look at this before today, but I raised PR #87 to fix the behaviour.

**Comment by kyeotic** [comment]
Hey @yenoiwesa, sorry this sat here for so long... its been a rough month. I've [released the fix](https://github.com/kyeotic/raviger/releases/tag/v2.1.0).

```
npm i raviger@2.1.0
```

**Comment by yenoiwesa** [comment]
Thanks a lot! I have updated our project to use `2.1.0` and that fixed the problem :-)
